env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  no-var:
    - error
  no-unused-vars:
    - off
  no-console:
    - off
